---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenjiamin.
--- DateTime: 2021/9/9 12:22 上午
---

-- 对应的类型
--print(type("Hello world"))
--print(type(10.4*3))
--print(type(print))
--print(type(type))
--print(type(true))
--print(type(nil))
--print(type(type(X)))

-- 用 nil 删除
tab1 = { key1 = "val1", key2 = "val2", "test", "val3", "val4" }
for k, v in pairs(tab1) do
    print(k .. " - " .. v)
end

tab1.key1 = nil
for k, v in pairs(tab1) do
    print(k .. " - " .. v)
end

-- 与 nil 做比较要加 ""
print(type(x) == nil)
print(type(x) == "nil")