---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenjiamin.
--- DateTime: 2021/10/9 2:36 下午
---

-- 局部变量和全局变量
print("局部变量和全局变量")
a = 5               -- 全局变量
local b = 5         -- 局部变量

function joke()
    c = 5           -- 全局变量
    local d = 6     -- 局部变量
end

joke()
print(c,d)          --> 5 nil

do
    local a = 6     -- 局部变量
    b = 6           -- 对局部变量重新赋值
    print(a,b);     --> 6 6
end

print(a,b)      --> 5 6

-- 赋值语句
print("赋值语句")


