---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenjiamin.
--- DateTime: 2021/9/9 12:04 上午
---

print("hello world!")
print("chenjiamin")

--[[
 多行注释
 多行注释
 --]]

-- 变量没有初始化也可以被访问，为 nil
print(a)

b = 10
print(b)

-- 删除变量，将变量置为 nil
b = nil
print(b)